dataset: 14res
max_size: 30000
min_freq: 1
val_rate: 0.2
glove_path: ./data/glove.840B.300d.txt
embed_size: 300
bio_embed_size: 100
kernel_sizes: [3, 4, 5]
kernel_num: 100
dropout: 0.1
num_epoches: 20
batch_size: 64
learning_rate: 0.001
gpu: 0